# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_nn_corr_internal <- function(corrMat, m) {
    .Call('_VeccTMVN_find_nn_corr_internal', PACKAGE = 'VeccTMVN', corrMat, m)
}

mvndns <- function(a, b, NN, muCond, muCoeff, condSd, beta, NLevel1, NLevel2) {
    .Call('_VeccTMVN_mvndns', PACKAGE = 'VeccTMVN', a, b, NN, muCond, muCoeff, condSd, beta, NLevel1, NLevel2)
}

mvnrnd <- function(a, b, NN, muCond, muCoeff, condSd, beta, N) {
    .Call('_VeccTMVN_mvnrnd', PACKAGE = 'VeccTMVN', a, b, NN, muCond, muCoeff, condSd, beta, N)
}

psi <- function(a, b, NN, muCond, muCoeff, condSd, beta, x) {
    .Call('_VeccTMVN_psi', PACKAGE = 'VeccTMVN', a, b, NN, muCond, muCoeff, condSd, beta, x)
}

mvtdns <- function(a, b, nu, NN, muCond, muCoeff, condSd, beta, NLevel1, NLevel2) {
    .Call('_VeccTMVN_mvtdns', PACKAGE = 'VeccTMVN', a, b, nu, NN, muCond, muCoeff, condSd, beta, NLevel1, NLevel2)
}

mvtrnd <- function(a, b, nu, NN, muCoeff, condSd, beta, N) {
    .Call('_VeccTMVN_mvtrnd', PACKAGE = 'VeccTMVN', a, b, nu, NN, muCoeff, condSd, beta, N)
}

sp_mat_mul_query <- function(queryRow, queryCol, idx, cidx, val) {
    .Call('_VeccTMVN_sp_mat_mul_query', PACKAGE = 'VeccTMVN', queryRow, queryCol, idx, cidx, val)
}

#' Univariate variable reordering, described in Genz and Bretz (2009)
#' If failed due to PD singularity, the unfinished order will be returned 
#' and a warning will be issued
#'
#' @param a lower integration limits
#' @param b upper integration limits
#' @param sigma covariance matrix
#' @return the new order
#' @export
univar_order <- function(a, b, sigma) {
    .Call('_VeccTMVN_univar_order', PACKAGE = 'VeccTMVN', a, b, sigma)
}

univar_order_vecc <- function(a, b, corrMat, m) {
    .Call('_VeccTMVN_univar_order_vecc', PACKAGE = 'VeccTMVN', a, b, corrMat, m)
}

